<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>BetterAutoGrabber</AssemblyName>
    <RootNamespace>BetterAutoGrabber</RootNamespace>
    <EnableHarmony>true</EnableHarmony>
    <!-- net6.0 is out of support for the SDK, but it's what SMAPI/the game target -->
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

</Project>
